version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - "8000:8080"
    depends_on:
      - postgres
  postgres:
    platform: linux/x86_64
    image: "postgres"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DATABASE: assessment
      POSTGRES_USER: assessment
      POSTGRES_PASSWORD: assessment
      POSTGRES_ROOT_PASSWORD: assessment